### ISSUE TITLE
Read fails after some time

### ISSUE THREAD

**Issue by zlokomatic** [tsndr/MFRC522-python#1]
After like 40 reads in a row ( not a specific number it just happens after some time ) not tags can be read anymore. 
System is a fresh raspian on a raspberry zero w

**Comment by tsndr** [comment]
Did a restart of the script fix the issue?

**Comment by zlokomatic** [comment]
Yes. After restarting the script everything works again

**Comment by tsndr** [comment]
Thanks for reporting your issue, i'll look into that.

**Comment by fintzd** [comment]
> Thanks for reporting your issue, i'll look into that.

Hey @tsndr !  

Thank you for publishing this repo! Was just wondering what the issue was (if you figured it out)? I'm using another repo to deal with the reader now, but basically the same issue is happening there, just not really depending on the amount of reads, but more like after some random time.

Cheers!

**Comment by tsndr** [comment]
@fintzd I honestly don't know, I wasn't able to reproduce it, sorry :/

**Comment by fintzd** [comment]
> @fintzd I honestly don't know, I wasn't able to reproduce it, sorry :/

No worries! And many thanks for the faster than light reply @tsndr ! Cheers mate!
